# Generated by Django 4.1.3 on 2022-11-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=15)),
                ('keywords', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('current_capacity', models.PositiveIntegerField(default=0)),
                ('weekday', models.CharField(max_length=2, null=True)),
                ('frequency2', models.CharField(max_length=15, null=True)),
                ('start_date', models.CharField(max_length=10, null=True)),
                ('end_date', models.CharField(max_length=10, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateTimeField(null=True)),
                ('studio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='UserAndClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.gymclass')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
