# Generated by Django 4.1.3 on 2022-11-20 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userandclass',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userandclass',
            name='gym_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
