# Generated by Django 4.1.3 on 2022-12-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='start_time',
            field=models.TimeField(default='04:35:58'),
        ),
    ]
