# Generated by Django 4.1.3 on 2022-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
