# Generated by Django 4.1.3 on 2022-11-19 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='studio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
