# Generated by Django 4.1.3 on 2022-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_gymclass_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='start_time',
            field=models.TimeField(default='04:36:02'),
        ),
    ]
