# Generated by Django 4.1.3 on 2022-11-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_userandclass_user_alter_class_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='coach',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
