# Generated by Django 4.1.3 on 2022-11-19 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_remove_class_studio_remove_class_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='studio',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
        ),
        migrations.AddField(
            model_name='class',
            name='users',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
