# Generated by Django 4.1.3 on 2022-11-20 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_coach_alter_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='recurrences',
        ),
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='weekday',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
