# Generated by Django 4.1.3 on 2022-11-16 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card', models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(23)])),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.card')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('charge_every', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('card_information', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.card')),
                ('payment_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.payments')),
                ('subscription', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptions')),
            ],
        ),
    ]
