# Generated by Django 4.1.3 on 2022-11-20 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usersub',
            old_name='valid',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='usersub',
            name='payment_history',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersub',
            name='renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersub',
            name='renew_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersub',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='charge_every',
            field=models.CharField(choices=[('Month', 'mon'), ('Year', 'yea')], default='Month', max_length=5),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.card'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptions'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
