# Generated by Django 4.1.3 on 2022-11-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='amenityset',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='amenityset',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='amenityset',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='imageset',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imageset',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imageset',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='images',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='AmenitySet',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageSet',
        ),
        migrations.AddField(
            model_name='images',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
        ),
        migrations.AddField(
            model_name='amenities',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
        ),
    ]
