# Generated by Django 4.1.3 on 2022-11-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_amenities_images_alter_amenityset_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='postal',
            new_name='postal_code',
        ),
    ]
